"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "@/lib/api";

const API_BASE=process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/,"")??"";
const DEFAULT_ORG=process.env.NEXT_PUBLIC_ORGANIZATION_ID??"";
type Application={id:string;candidate_id:string;job_id:string;status:string};
type Candidate={id:string;first_name:string;last_name?:string|null};
type Job={id:string;title:string};
type Offer={id:string;application_id:string;title:string;status:string;employment_type?:string|null;start_date?:string|null;salary_amount?:number|null;salary_currency?:string|null};
const transitions:Record<string,string[]>={draft:["sent","withdrawn"],sent:["accepted","rejected","withdrawn","expired"],accepted:[],rejected:[],withdrawn:[],expired:[]};
const name=(c?:Candidate)=>c?[c.first_name,c.last_name].filter(Boolean).join(" "):"Unknown candidate";
export default function OffersPage(){
 const [items,setItems]=useState<Offer[]>([]),[apps,setApps]=useState<Application[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[jobs,setJobs]=useState<Job[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[showCreate,setShowCreate]=useState(false),[saving,setSaving]=useState(false);
 const [applicationId,setApplicationId]=useState(""),[title,setTitle]=useState(""),[employmentType,setEmploymentType]=useState("Permanent"),[startDate,setStartDate]=useState(""),[salary,setSalary]=useState(""),[currency,setCurrency]=useState("GBP");
 const org=typeof window!=="undefined"?(window.localStorage.getItem("talentos_active_org")||DEFAULT_ORG):DEFAULT_ORG;
 const appMap=useMemo(()=>new Map(apps.map(a=>[a.id,a])),[apps]),candidateMap=useMemo(()=>new Map(candidates.map(c=>[c.id,c])),[candidates]),jobMap=useMemo(()=>new Map(jobs.map(j=>[j.id,j])),[jobs]);
 const load=async()=>{try{const q=encodeURIComponent(org);const [or,ar,cr,jr]=await Promise.all([apiFetch(API_BASE+`/api/offers?organization_id=${q}`),apiFetch(API_BASE+`/api/applications?organization_id=${q}`),apiFetch(API_BASE+`/api/candidates?organization_id=${q}`),apiFetch(API_BASE+`/api/jobs?organization_id=${q}`)]);if(!or.ok||!ar.ok||!cr.ok||!jr.ok)throw new Error("Unable to load offer workspace.");setItems(await or.json());setApps(await ar.json());setCandidates(await cr.json());setJobs(await jr.json())}catch(e){setMessage(e instanceof Error?e.message:"Unable to load offers.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const label=(id:string)=>{const a=appMap.get(id);return a?`${name(candidateMap.get(a.candidate_id))} — ${jobMap.get(a.job_id)?.title??"Unknown job"}`:id};
 async function create(e:React.FormEvent){e.preventDefault();if(!applicationId||!title){setMessage("Select an application and enter an offer title.");return}setSaving(true);try{const r=await apiFetch(API_BASE+"/api/offers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organization_id:org,application_id:applicationId,title,status:"draft",employment_type:employmentType,start_date:startDate||null,salary_amount:salary?Number(salary):null,salary_currency:currency})});if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.detail??"Unable to create offer.")}setShowCreate(false);setApplicationId("");setTitle("");setStartDate("");setSalary("");setMessage("Offer created as draft.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to create offer.")}finally{setSaving(false)}}
 async function change(item:Offer,status:string){if(status===item.status||!transitions[item.status]?.includes(status)){setMessage("That offer transition is not allowed.");return}const r=await apiFetch(API_BASE+"/api/offers/"+item.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok){const d=await r.json().catch(()=>null);setMessage(d?.detail??"Unable to update offer.");return}setItems(xs=>xs.map(x=>x.id===item.id?{...x,status}:x));setMessage("")}
 return <main className="p-8"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-semibold">Offers</h1><p className="mt-2 text-sm text-gray-500">Create and track offers from draft through acceptance.</p></div><button className="btn primary" onClick={()=>setShowCreate(true)}>+ New offer</button></div>
 {message&&<div className="notice mt-4">{message}</div>}
 {showCreate&&<div className="modal-backdrop"><form className="modal" onSubmit={create}><div className="card-head"><span className="card-title">New offer</span><button type="button" className="icon-button" onClick={()=>setShowCreate(false)}>×</button></div><label>Application<select required value={applicationId} onChange={e=>setApplicationId(e.target.value)}><option value="">Select candidate / job</option>{apps.filter(a=>["interview","offer"].includes(a.status)).map(a=><option key={a.id} value={a.id}>{label(a.id)}</option>)}</select></label><label>Offer title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Senior Software Engineer"/></label><label>Employment type<input value={employmentType} onChange={e=>setEmploymentType(e.target.value)}/></label><label>Start date<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><div className="grid grid-cols-2 gap-3"><label>Salary<input type="number" min="0" value={salary} onChange={e=>setSalary(e.target.value)}/></label><label>Currency<input value={currency} maxLength={3} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label></div><div className="modal-actions"><button type="button" className="btn" onClick={()=>setShowCreate(false)}>Cancel</button><button className="btn primary" disabled={saving}>{saving?"Creating...":"Create draft"}</button></div></form></div>}
 <div className="mt-8 overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead><tr className="border-b bg-gray-50"><th className="p-4">Candidate / Job</th><th className="p-4">Offer</th><th className="p-4">Salary</th><th className="p-4">Start date</th><th className="p-4">Status</th></tr></thead><tbody>{loading?<tr><td className="p-4" colSpan={5}>Loading…</td></tr>:items.map(o=><tr key={o.id} className="border-b"><td className="p-4"><Link className="font-medium" href="/submissions">{label(o.application_id)}</Link></td><td className="p-4">{o.title}</td><td className="p-4">{o.salary_amount!=null?`${o.salary_currency||""} ${o.salary_amount}`:"—"}</td><td className="p-4">{o.start_date||"—"}</td><td className="p-4"><select className="filter" value={o.status} onChange={e=>void change(o,e.target.value)}><option value={o.status}>{o.status}</option>{(transitions[o.status]??[]).map(s=><option key={s} value={s}>{s}</option>)}</select></td></tr>)}{!loading&&!items.length&&<tr><td className="p-4 text-gray-500" colSpan={5}>No offers yet.</td></tr>}</tbody></table></div></main>
}
