"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "@/lib/api";

const API_BASE = process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/, "") ?? "";
const DEFAULT_ORG = process.env.NEXT_PUBLIC_ORGANIZATION_ID ?? "";

type Application={id:string;candidate_id:string;job_id:string;status:string};
type Candidate={id:string;first_name:string;last_name?:string|null};
type Job={id:string;title:string};
type Interview={id:string;application_id:string;scheduled_at:string;duration_minutes:number;interview_type:string;location?:string|null;status:string;notes?:string|null};

const transitions:Record<string,string[]>={scheduled:["completed","cancelled","rescheduled","no_show"],rescheduled:["completed","cancelled","rescheduled","no_show"],completed:[],cancelled:[],no_show:[]};
const name=(c?:Candidate)=>c?[c.first_name,c.last_name].filter(Boolean).join(" "):"Unknown candidate";

export default function InterviewsPage(){
 const [items,setItems]=useState<Interview[]>([]),[apps,setApps]=useState<Application[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[jobs,setJobs]=useState<Job[]>([]);
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(""),[showCreate,setShowCreate]=useState(false),[saving,setSaving]=useState(false);
 const [applicationId,setApplicationId]=useState(""),[scheduledAt,setScheduledAt]=useState(""),[type,setType]=useState("video"),[duration,setDuration]=useState("60"),[location,setLocation]=useState("");
 const org=typeof window!=="undefined"?(window.localStorage.getItem("talentos_active_org")||DEFAULT_ORG):DEFAULT_ORG;
 const appMap=useMemo(()=>new Map(apps.map(a=>[a.id,a])),[apps]), candidateMap=useMemo(()=>new Map(candidates.map(c=>[c.id,c])),[candidates]), jobMap=useMemo(()=>new Map(jobs.map(j=>[j.id,j])),[jobs]);
 const load=async()=>{try{const q=encodeURIComponent(org);const [ir,ar,cr,jr]=await Promise.all([apiFetch(API_BASE+`/api/interviews?organization_id=${q}`),apiFetch(API_BASE+`/api/applications?organization_id=${q}`),apiFetch(API_BASE+`/api/candidates?organization_id=${q}`),apiFetch(API_BASE+`/api/jobs?organization_id=${q}`)]);if(!ir.ok||!ar.ok||!cr.ok||!jr.ok)throw new Error("Unable to load interview workspace.");setItems(await ir.json());setApps(await ar.json());setCandidates(await cr.json());setJobs(await jr.json())}catch(e){setMessage(e instanceof Error?e.message:"Unable to load interviews.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const label=(id:string)=>{const a=appMap.get(id);return a?`${name(candidateMap.get(a.candidate_id))} — ${jobMap.get(a.job_id)?.title??"Unknown job"}`:id};
 async function create(e:React.FormEvent){e.preventDefault();if(!applicationId||!scheduledAt){setMessage("Select an application and interview time.");return}setSaving(true);try{const r=await apiFetch(API_BASE+"/api/interviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organization_id:org,application_id:applicationId,scheduled_at:new Date(scheduledAt).toISOString(),duration_minutes:Number(duration),interview_type:type,location:location||null,status:"scheduled"})});if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.detail??"Unable to schedule interview.")}setShowCreate(false);setApplicationId("");setScheduledAt("");setLocation("");setMessage("Interview scheduled.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to schedule interview.")}finally{setSaving(false)}}
 async function change(item:Interview,status:string){if(status===item.status||!transitions[item.status]?.includes(status)){setMessage("That interview transition is not allowed.");return}const r=await apiFetch(API_BASE+"/api/interviews/"+item.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok){const d=await r.json().catch(()=>null);setMessage(d?.detail??"Unable to update interview.");return}setItems(xs=>xs.map(x=>x.id===item.id?{...x,status}:x));setMessage("")}
 return <main className="p-8"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-semibold">Interviews</h1><p className="mt-2 text-sm text-gray-500">Schedule and manage candidate interviews.</p></div><button className="btn primary" onClick={()=>setShowCreate(true)}>+ Schedule interview</button></div>
 {message&&<div className="notice mt-4">{message}</div>}
 {showCreate&&<div className="modal-backdrop"><form className="modal" onSubmit={create}><div className="card-head"><span className="card-title">Schedule interview</span><button type="button" className="icon-button" onClick={()=>setShowCreate(false)}>×</button></div><label>Application<select required value={applicationId} onChange={e=>setApplicationId(e.target.value)}><option value="">Select candidate / job</option>{apps.filter(a=>!["rejected","withdrawn","hired"].includes(a.status)).map(a=><option key={a.id} value={a.id}>{label(a.id)}</option>)}</select></label><label>Date & time<input required type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option>video</option><option>phone</option><option>onsite</option></select></label><label>Duration (minutes)<input type="number" min="15" max="480" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label>Location / meeting link<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Optional"/></label><div className="modal-actions"><button type="button" className="btn" onClick={()=>setShowCreate(false)}>Cancel</button><button className="btn primary" disabled={saving}>{saving?"Scheduling...":"Schedule"}</button></div></form></div>}
 <div className="mt-8 overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead><tr className="border-b bg-gray-50"><th className="p-4">Scheduled</th><th className="p-4">Candidate / Job</th><th className="p-4">Type</th><th className="p-4">Duration</th><th className="p-4">Status</th></tr></thead><tbody>{loading?<tr><td className="p-4" colSpan={5}>Loading…</td></tr>:items.map(i=><tr key={i.id} className="border-b"><td className="p-4">{new Date(i.scheduled_at).toLocaleString()}</td><td className="p-4"><Link className="font-medium" href="/submissions">{label(i.application_id)}</Link></td><td className="p-4">{i.interview_type}</td><td className="p-4">{i.duration_minutes} min</td><td className="p-4"><select className="filter" value={i.status} onChange={e=>void change(i,e.target.value)}><option value={i.status}>{i.status}</option>{(transitions[i.status]??[]).map(s=><option key={s} value={s}>{s}</option>)}</select></td></tr>)}{!loading&&!items.length&&<tr><td className="p-4 text-gray-500" colSpan={5}>No interviews yet.</td></tr>}</tbody></table></div></main>
}
