"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "@/lib/api";

const API_BASE=process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/,"")??"";
const DEFAULT_ORG=process.env.NEXT_PUBLIC_ORGANIZATION_ID??"";
type Application={id:string;candidate_id:string;job_id:string;status:string};
type Candidate={id:string;first_name:string;last_name?:string|null};
type Job={id:string;title:string};
type Client={id:string;name:string};
type Placement={id:string;candidate_id:string;job_id:string;client_id?:string|null;status:string;start_date:string;end_date?:string|null;fee_amount?:number|null;fee_currency?:string|null;fee_type?:string|null};
const transitions:Record<string,string[]>={pending:["active","cancelled"],active:["completed","cancelled"],completed:[],cancelled:[]};
const name=(c?:Candidate)=>c?[c.first_name,c.last_name].filter(Boolean).join(" "):"Unknown candidate";
export default function PlacementsPage(){
 const [items,setItems]=useState<Placement[]>([]),[apps,setApps]=useState<Application[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[jobs,setJobs]=useState<Job[]>([]),[clients,setClients]=useState<Client[]>([]);
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(""),[showCreate,setShowCreate]=useState(false),[saving,setSaving]=useState(false);
 const [applicationId,setApplicationId]=useState(""),[clientId,setClientId]=useState(""),[startDate,setStartDate]=useState(""),[fee,setFee]=useState(""),[currency,setCurrency]=useState("GBP"),[feeType,setFeeType]=useState("fixed");
 const org=typeof window!=="undefined"?(window.localStorage.getItem("talentos_active_org")||DEFAULT_ORG):DEFAULT_ORG;
 const appMap=useMemo(()=>new Map(apps.map(a=>[a.id,a])),[apps]),candidateMap=useMemo(()=>new Map(candidates.map(c=>[c.id,c])),[candidates]),jobMap=useMemo(()=>new Map(jobs.map(j=>[j.id,j])),[jobs]),clientMap=useMemo(()=>new Map(clients.map(c=>[c.id,c])),[clients]);
 const load=async()=>{try{const q=encodeURIComponent(org);const [pr,ar,cr,jr,clr]=await Promise.all([apiFetch(API_BASE+`/api/placements?organization_id=${q}`),apiFetch(API_BASE+`/api/applications?organization_id=${q}`),apiFetch(API_BASE+`/api/candidates?organization_id=${q}`),apiFetch(API_BASE+`/api/jobs?organization_id=${q}`),apiFetch(API_BASE+`/api/clients?organization_id=${q}`)]);if(!pr.ok||!ar.ok||!cr.ok||!jr.ok||!clr.ok)throw new Error("Unable to load placement workspace.");setItems(await pr.json());setApps(await ar.json());setCandidates(await cr.json());setJobs(await jr.json());setClients(await clr.json())}catch(e){setMessage(e instanceof Error?e.message:"Unable to load placements.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const label=(id:string)=>{const a=appMap.get(id);return a?`${name(candidateMap.get(a.candidate_id))} — ${jobMap.get(a.job_id)?.title??"Unknown job"}`:id};
 async function create(e:React.FormEvent){e.preventDefault();if(!applicationId||!startDate){setMessage("Select an application and start date.");return}setSaving(true);try{const a=appMap.get(applicationId);if(!a){throw new Error("Application not found.")}const r=await apiFetch(API_BASE+"/api/placements",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organization_id:org,application_id:applicationId,job_id:a.job_id,candidate_id:a.candidate_id,client_id:clientId||null,status:"pending",start_date:startDate,end_date:null,fee_amount:fee?Number(fee):null,fee_currency:currency,fee_type:feeType})});if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.detail??"Unable to create placement.")}setShowCreate(false);setApplicationId("");setClientId("");setStartDate("");setFee("");setMessage("Placement created as pending.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to create placement.")}finally{setSaving(false)}}
 async function change(item:Placement,status:string){if(status===item.status||!transitions[item.status]?.includes(status)){setMessage("That placement transition is not allowed.");return}const r=await apiFetch(API_BASE+"/api/placements/"+item.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok){const d=await r.json().catch(()=>null);setMessage(d?.detail??"Unable to update placement.");return}setItems(xs=>xs.map(x=>x.id===item.id?{...x,status}:x));setMessage("")}
 return <main className="p-8"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-semibold">Placements</h1><p className="mt-2 text-sm text-gray-500">Track successful hires, clients and recruitment fees.</p></div><button className="btn primary" onClick={()=>setShowCreate(true)}>+ New placement</button></div>
 {message&&<div className="notice mt-4">{message}</div>}
 {showCreate&&<div className="modal-backdrop"><form className="modal" onSubmit={create}><div className="card-head"><span className="card-title">New placement</span><button type="button" className="icon-button" onClick={()=>setShowCreate(false)}>×</button></div><label>Application<select required value={applicationId} onChange={e=>setApplicationId(e.target.value)}><option value="">Select candidate / job</option>{apps.filter(a=>a.status==="hired").map(a=><option key={a.id} value={a.id}>{label(a.id)}</option>)}</select></label><label>Client<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">No client / direct</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Start date<input required type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><div className="grid grid-cols-3 gap-3"><label>Fee<input type="number" min="0" value={fee} onChange={e=>setFee(e.target.value)}/></label><label>Currency<input value={currency} maxLength={3} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label><label>Fee type<select value={feeType} onChange={e=>setFeeType(e.target.value)}><option value="fixed">Fixed</option><option value="percentage">Percentage</option></select></label></div><div className="modal-actions"><button type="button" className="btn" onClick={()=>setShowCreate(false)}>Cancel</button><button className="btn primary" disabled={saving}>{saving?"Creating...":"Create placement"}</button></div></form></div>}
 <div className="mt-8 overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead><tr className="border-b bg-gray-50"><th className="p-4">Candidate</th><th className="p-4">Job</th><th className="p-4">Client</th><th className="p-4">Start</th><th className="p-4">Fee</th><th className="p-4">Status</th></tr></thead><tbody>{loading?<tr><td className="p-4" colSpan={6}>Loading…</td></tr>:items.map(p=>{const a=appMap.get(p.id)||undefined;return <tr key={p.id} className="border-b"><td className="p-4">{name(candidateMap.get(p.candidate_id))}</td><td className="p-4">{jobMap.get(p.job_id)?.title??"Unknown job"}</td><td className="p-4">{p.client_id?clientMap.get(p.client_id)?.name??"Unknown client":"Direct"}</td><td className="p-4">{p.start_date}</td><td className="p-4">{p.fee_amount!=null?`${p.fee_currency||""} ${p.fee_amount}${p.fee_type==="percentage"?"%":""}`:"—"}</td><td className="p-4"><select className="filter" value={p.status} onChange={e=>void change(p,e.target.value)}><option value={p.status}>{p.status}</option>{(transitions[p.status]??[]).map(s=><option key={s} value={s}>{s}</option>)}</select></td></tr>})}{!loading&&!items.length&&<tr><td className="p-4 text-gray-500" colSpan={6}>No placements yet.</td></tr>}</tbody></table></div></main>
}
